# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20170810_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pic_uploads/')),
                ('scroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Scroll')),
            ],
        ),
    ]
