# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='pic',
            new_name='image',
        ),
    ]
