# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20170810_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='scroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Scroll'),
        ),
    ]
