# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20170810_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
