# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20170810_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mic',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
